# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dffcbc250ee65011a95adccb17384707825ce1a9b68baf02805c05814f31797df6ad32727a1597ef6d9bb11582f6541554bbf68f83f1d2555fefdf03fd3584cf

test:
  secret_key_base: b46fd5d422a699101395c20c06cc95fc31d295daa7e146843e2ce352c889a2f764b2e959bfa373d995d2f65004c8fd991eac4ce57aef52d6b0b54c32aaf6beb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
